<a href="https://colab.research.google.com/github/sofiahlr/Linear-Algebra-58019/blob/main/Final_Exam.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Problem 1. Student A, Student B, and Student C have a total of Php 89 cash in their banks. Student A has 6 less than Student C. Student B has 3 times what Student C has. How much does each student have? (30 points)

In [3]:
import numpy as np
eq1 =  np.array([[1,1,1],[1,0,4],[0,0,5]])
eq2 = np.array([[89,],[89],[95]])

amt = np.linalg.inv(eq1).dot(eq2)
print(amt)


[[13.]
 [57.]
 [19.]]


What property of matrix that can not be done solved by any method in solving Linear Equations. (30 points)

The property of matrix that can not be done solved by any method in solving Linear Equations is singular matrix. If a square matrix has no inverse, it is singular. A matrix is singular if its determinant is 0.

Problem 3. Consider the matrix, (40 points)

1. Find the eigenvalue/s
2. Find the eigenvectors

In [1]:
import numpy as np 
from numpy.linalg import eig

A = np.array([[8,5,-6],[-12,-9,12],[-3,-3,5]])
print(A)

w,v = np.linalg.eig(A)
print("The eigenvaalues is/are:",w)
print("The eigenvectors are:",v)

x = v.round()
print(x)


[[  8   5  -6]
 [-12  -9  12]
 [ -3  -3   5]]
The eigenvaalues is/are: [-1.  3.  2.]
The eigenvectors are: [[ 3.01511345e-01 -7.07106781e-01  7.07106781e-01]
 [-9.04534034e-01  7.07106781e-01  1.53837015e-15]
 [-3.01511345e-01 -2.26120075e-15  7.07106781e-01]]
[[ 0. -1.  1.]
 [-1.  1.  0.]
 [-0. -0.  1.]]
