<a href="https://colab.research.google.com/github/sofiahlr/Linear-Algebra-58019/blob/main/Practical_Lab_Exam_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Practical Lab Exam 1

In [6]:
import numpy as np
A = np.array([[1,2,3],[4,5,5]])
B = np.array([[1,2],[3,4],[5,6]])

dot = np.dot(A,B)
print(dot)

[[22 28]
 [44 58]]


In [11]:
import numpy as np
D = np.array([[1,2],[3,4]])

print(D+D)

[[2 4]
 [6 8]]


In [7]:
import numpy as np
C = np.array([[1,2,3],[4,5,6],[7,8,9]])

print(2*C)

[[ 2  4  6]
 [ 8 10 12]
 [14 16 18]]


In [12]:
import numpy as np
A = np.array([5,3,-1])

print(A.size)

print(type(A))

print(A.shape)

print(A.ndim)


3
<class 'numpy.ndarray'>
(3,)
1
