<a href="https://colab.research.google.com/github/sofiahlr/Linear-Algebra-58019/blob/main/Prelim_Exam.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
c = np.ones((4, 4))

c[::2, 1::2] = 2
c[1::2, ::2] = 3
print(c)

[[1. 2. 1. 2.]
 [3. 1. 3. 1.]
 [1. 2. 1. 2.]
 [3. 1. 3. 1.]]


In [2]:
import numpy as np
c = np.ones((4, 4))

c[::2, 1::2] = 2
c[1::2, ::2] = 3
print(c*2)

[[2. 4. 2. 4.]
 [6. 2. 6. 2.]
 [2. 4. 2. 4.]
 [6. 2. 6. 2.]]


In [3]:
import numpy as np

A = (([2,7,4])) 
B = (([3,9,8]))

output = np.cross(A,B)
print(output)

[20 -4 -3]
